### ISSUE TITLE
Python 3.12

### ISSUE THREAD

**Issue by dunossauro** [dunossauro/fastapi-do-zero#118]
Issue para acumular problemas referentes ao usar o python 3.12

- utcnow -> utc + tz (https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow) #121 
- Blue não suporta a sintaxe de generics (embora não seja usado no curso, foi notificado)
  - Subistituir pelo ruff formater? Tenho opniões batante adversas a isso como #111 
- Alteração no comando do ruff #116

PS: Ainda tem mais por vir...

**Comment by dunossauro** [comment]
Possível solução para alterar a dupla blue + isort pelo ruff

```toml
[tool.ruff]
line-length = 79
exclude = ['.venv', 'migrations']

[tool.ruff.lint]
preview = true
select = ['I', 'F', 'E', 'W', 'PL', 'PT']
explicit-preview-rules = true

[tool.ruff.format]
preview = true
quote-style = 'single'
```
