### ISSUE TITLE
Remover warnings do Pytest

### ISSUE THREAD

**Issue by dunossauro** [dunossauro/fastapi-do-zero#122]
Diversas dúvidas abertas sobre o warning levantado sobre o `crypt`. Pessoas iniciantes podem confundir os warnings com erros na configuração do ambiente.

Adicionar a linha a seguir:

```toml
[tool.pytest.ini_options]
pythonpath = "."
addopts = '-p no:warnings'
```

Isso deve ser feito no texto da aula 01 e propagado no código das aulas restantes.
