### ISSUE TITLE
Configuração do taskipy na aula 1

### ISSUE THREAD

**Issue by ivansantiagojr** [dunossauro/fastapi-do-zero#153]
Na aula 01 a configuração do taskipy é a seguinte:
```toml
[tool.taskipy.tasks]
lint = 'ruff check . && ruff check . --diff'
format = 'ruff check . --fix && ruff format .'
run = 'fastapi dev fast_zero/app.py'
pre_test = 'task lint'
test = 'pytest -s -x --cov=fast_zero -vv'
post_test = 'coverage html'
```

E no código das aulas assim:
```toml
[tool.taskipy.tasks]
lint = 'ruff check .; ruff check . --diff'
format = 'ruff check . --fix; ruff format .'
run = 'fastapi dev fast_zero/app.py'
pre_test = 'task lint'
test = 'pytest -s -x --cov=fast_zero -vv'
post_test = 'coverage html'
```
Acredito que esqueceu de mudar no texto da aula, lembro que fez essa alteração em live para que caso o primeiro comando resulte em erro, o segundo ainda seja executado.
