### ISSUE TITLE
Compatibilidade com OCI

### ISSUE THREAD

**Issue by dunossauro** [dunossauro/fastapi-do-zero#333]
## Resumo

A ideia dessa issue é substituir os nomes das coisas específicas de docker.

Como `Dockerfile` para `Containerfile` (não oci) e adaptar o `compose.yaml` (que já está em OCI) para suportar o Containerfile.

A adaptação é bastante simples no compose:

```yaml
services:
  fastzero_database:
    image: docker.io/postgres  # especificar que é uma iamgem do hub do docker
# ...
  fastzero_app:
    image: fastzero_app
    entrypoint: ./entrypoint.sh
    build:
      context: .
      dockerfile: Containerfile
```

A ideia não é remover o docker do curso, nem mesmo suportar o podman, mas manter a compatibilidade entre as ferramentas.

## Onde isso deve ser feito?

Isso deve ser feito no texto da aula 10 e nos códigos-fonte de 10, 11, 12 e 13.

---

Comentários podem ser adicionados em relação a usar o podman (um Admonition deve ser o suficiente)

Uma nota na deploy do fly.io também pode ser adicionada, caso alguém escolha usar o podman. Já que uma nota como essa já foi adicionada à nota do `act`:

https://community.fly.io/t/howto-use-podman-instead-of-docker-for-local-builds-and-uploading-container-images/542/12
